language: python
python:
  - 3.5
services:
  - postgresql
  - docker
sudo: required
addons:
  postgresql: "9.4"
cache: pip
before_install:
  - createdb -U postgres deis
install:
  - pip install -r rootfs/requirements.txt
  - pip install -r rootfs/dev_requirements.txt
script:
  - make test
after_success:
  - pushd rootfs/ && codecov && popd
